version: '2.0'

services:
  locator-svc:
    build:
      context: .
    container_name: locator-svc
    hostname: locator-svc
    env_file: .env.prod
    ports:
      - "${LOCATOR_SVC_PORT:-8080}:8080"