// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Sam Komarov",
            "url": "github.com/k0marov",
            "email": "sam@skomarov.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/locator/missing": {
            "get": {
                "description": "Given a geo location, returns a list of people from LizaAlertAPI,\nordered by their relevance (calculated from distance and days missing) to provided location.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "locator"
                ],
                "summary": "Get info about relevant missing people",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Geo location latitude",
                        "name": "latitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Geo location longitude",
                        "name": "longitude",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/delivery.MissingPersonResponse"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "delivery.MissingPersonResponse": {
            "type": "object",
            "properties": {
                "photo_url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "sber.skomarov.com",
	BasePath:         "/api/v1",
	Schemes:          []string{"https", "http"},
	Title:            "Locator API",
	Description:      "An API for getting the most relevant missing people info from LizaAlerts.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
