basePath: /api/v1
definitions:
  delivery.MissingPersonResponse:
    properties:
      photo_url:
        type: string
    type: object
host: sber.skomarov.com
info:
  contact:
    email: sam@skomarov.com
    name: Sam Komarov
    url: github.com/k0marov
  description: An API for getting the most relevant missing people info from LizaAlerts.
  title: Locator API
  version: "1.0"
paths:
  /locator/missing:
    get:
      description: |-
        Given a geo location, returns a list of people from LizaAlertAPI,
        ordered by their relevance (calculated from distance and days missing) to provided location.
      parameters:
      - description: Geo location latitude
        in: query
        name: latitude
        required: true
        type: number
      - description: Geo location longitude
        in: query
        name: longitude
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/delivery.MissingPersonResponse'
            type: array
      summary: Get info about relevant missing people
      tags:
      - locator
schemes:
- https
- http
swagger: "2.0"
